#!/bin/bash

target=$1
mkdir -p $(dirname $target)
base=$(basename $target)

source=$(dirname $0)/$(echo $base | sed -n -e 's/\(.*\)-.*/\1.svg/p')
width=$(echo $base | sed -n -e 's/.*-\(.*\)x.*/\1/p')
height=$(echo $base | sed -n -e 's/.*x\(.*\)\..*/\1/p')

if test "$width" == ""; then
    scale=$(echo $base | sed -n -e 's/.*-\(.*\)\.png/\1/p')
    w1=$(grep viewBox $source | sed -e 's/.*\"0 0 \([0-9]\+\) \([0-9]\+\)\"/\1/')
    h1=$(grep viewBox $source | sed -e 's/.*\"0 0 \([0-9]\+\) \([0-9]\+\)\"/\2/')
    width=$(expr $w1 \* $scale / 100)
    height=$(expr $h1 \* $scale / 100)
fi

inkscape -f $source -e $target -C -w $width -h $height
